//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iCream_Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Book
    {
        public int book_id { get; set; }
        public string book_name { get; set; }
        public string book_discount { get; set; }
        public Nullable<int> book_price { get; set; }
        public Nullable<int> book_quantity { get; set; }
        public string book_img { get; set; }
        public HttpPostedFileBase book_imgFile { get; set; }
    }
}
