//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iCream_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category_Recipe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Category_Recipe()
        {
            this.Recipe_Viewer = new HashSet<Recipe_Viewer>();
        }
    
        public string category_name { get; set; }
        public Nullable<int> category_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recipe_Viewer> Recipe_Viewer { get; set; }
    }
}
