//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iCream_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_1
    {
        public string customer_id { get; set; }
        public string customer_name { get; set; }
        public string customer_pass { get; set; }
        public string customer_repass { get; set; }
        public string customer_email { get; set; }
        public Nullable<System.DateTime> customer_birthday { get; set; }
        public Nullable<int> customer_status { get; set; }
        public Nullable<int> customer_cardNumber { get; set; }
        public string customer_cardsName { get; set; }
        public Nullable<int> customer_cardCVV { get; set; }
    }
}
