//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iCream_Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class iCreamEntities : DbContext
    {
        public iCreamEntities()
            : base("name=iCreamEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Category_Recipe> Category_Recipe { get; set; }
        public virtual DbSet<Feedback> Feedbacks { get; set; }
        public virtual DbSet<Recipe_Viewer> Recipe_Viewer { get; set; }
        public virtual DbSet<FaQ> FaQs { get; set; }
        public virtual DbSet<Customer_1> Customer_1 { get; set; }
        public virtual DbSet<Book> Books { get; set; }
    }
}
