//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iCream_Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Recipe_Viewer
    {
        public int recipeV_id { get; set; }
        public string caterory_name { get; set; }
        public string recipeV_nameViewer { get; set; }
        public string recipeV_name { get; set; }
        public Nullable<int> recipeV_price { get; set; }
        public string recipeV_img { get; set; }
        public HttpPostedFileBase recipeV_imgFile { get; set; }
        public Nullable<int> recipe_status { get; set; }
        public string recipeV_text { get; set; }
    
        public virtual Category_Recipe Category_Recipe { get; set; }
    }
}
