//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iCream_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FaQ
    {
        public int faq_id { get; set; }
        public Nullable<int> faq_type { get; set; }
        public string faq_nameViewer { get; set; }
        public string faq_email { get; set; }
        public Nullable<int> faq_phone { get; set; }
        public string faq_text { get; set; }
    }
}
